//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPConvertSR2.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPConvertSR2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Engines&gt;
        ///&lt;Part id=&quot;1&quot; partType=&quot;JetEngine1&quot; position=&quot;-0.3371329,3.446774,-3.593281&quot; rotation=&quot;-1.628447E-12,0,0&quot; name=&quot;JT-85&quot; activationStage=&quot;0&quot; commandPodId=&quot;1&quot; materials=&quot;0,0,2,3,4&quot; shroudStyle=&quot;JetEngineShroud-None&quot; nozzleStyle=&quot;Basic&quot; inletConeStyle=&quot;Spike&quot;&gt;
        ///        &lt;Drag drag=&quot;0.4687811,0.4694992,0.1249904,0.05263951,0.4820705,0.3201717&quot; area=&quot;0.6159285,0.6178063,0.1873614,0.1505582,0.6379199,0.4237916&quot; /&gt;
        ///        &lt;Config /&gt;
        ///        &lt;Fuselage bottomScale=&quot;0.25,0.25&quot; offset=&quot;0,0.5743403,0&quot; topSca [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Engines {
            get {
                return ResourceManager.GetString("Engines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Craft name=&quot;Example&quot; parent=&quot;&quot; initialBoundsMin=&quot;-1,-1,-1&quot; initialBoundsMax=&quot;1,1,1&quot; price=&quot;0&quot; suppressCraftConfigWarnings=&quot;false&quot; xmlVersion=&quot;11&quot; localCenterOfMass=&quot;0,0,0&quot;&gt;
        ///  &lt;Assembly&gt;
        ///    &lt;Parts&gt;
        ///      &lt;Part id=&quot;50&quot; partType=&quot;CommandPod1&quot; position=&quot;5.960464E-07,-4.768372E-07,2.69486&quot; rotation=&quot;90,1.295787E-05,0&quot; rootPart=&quot;true&quot; commandPodId=&quot;50&quot; materials=&quot;0,0,0,0,0&quot;&gt;
        ///        &lt;Drag drag=&quot;1.081415,0.02116543,1.227475,1.227475,1.124745,1.125364&quot; area=&quot;2.023688,0. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
    }
}
