//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SR2ConvertSP.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SR2ConvertSP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Craft name=&quot;Example&quot; parent=&quot;&quot; initialBoundsMin=&quot;-1,-1.000002,-6.789536&quot; initialBoundsMax=&quot;1,0.9999986,9.22415&quot; price=&quot;529658&quot; suppressCraftConfigWarnings=&quot;true&quot; xmlVersion=&quot;12&quot; localCenterOfMass=&quot;0,-6.157865,-9.536743E-07&quot;&gt;
        ///  &lt;Assembly&gt;
        ///    &lt;Parts&gt;
        ///      &lt;Part id=&quot;39&quot; partType=&quot;CommandPod1&quot; position=&quot;0,-1.907349E-06,-6.157866&quot; rotation=&quot;90,180,0&quot; rootPart=&quot;true&quot; commandPodId=&quot;39&quot; materials=&quot;0,0,0,0,0&quot;&gt;
        ///        &lt;Drag drag=&quot;0,1.02784,1.214433,1.214433,1.108501,1.1 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ExampleSR2 {
            get {
                return ResourceManager.GetString("ExampleSR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Aircraft name=&quot;Example&quot; url=&quot;&quot; theme=&quot;Custom&quot; size=&quot;5.67676,2.733356,5&quot; boundsMin=&quot;-5.17676,0,-0.75&quot; xmlVersion=&quot;6&quot; legacyJointIdentification=&quot;false&quot;&gt;
        ///  &lt;Assembly&gt;
        ///    &lt;Parts&gt;
        ///      &lt;Part id=&quot;1&quot; partType=&quot;Cockpit-1&quot; position=&quot;2.842171E-14,2.483356,0&quot; rotation=&quot;0,0,0&quot; drag=&quot;0.1278033,0.1278033,0.005840001,0.005840001,0.2579999,0.258&quot; materials=&quot;7,0&quot; partCollisionResponse=&quot;Default&quot;&gt;
        ///        &lt;Cockpit.State primaryCockpit=&quot;True&quot; lookBackTranslation=&quot;0,0&quot; /&gt;
        ///      &lt;/ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ExportTemplateSP {
            get {
                return ResourceManager.GetString("ExportTemplateSP", resourceCulture);
            }
        }
    }
}
